### PR TITLE
Add projects

### PR DESCRIPTION
**Pull request by ayushpateria**
I've modified/added some projects based on my discussion with the Gymkhana president.

### CODE REVIEW

**Review by CrazyByDefault — COMMENTED** [review]
Doesn't this feel like too many Dashboard things? Can't we have more interesting projects? We literally have 4 Dashboard projects with this.

**Comment by ayushpateria** [comment]
It is. But we have to incorporate these changes to have a full fledged application for IITH. I'm not quite sure about other projects. If you have any other ideas add them, I shall mentor them.

**Comment by CrazyByDefault** [comment]
This can be done later by some Lambda core member if necessary. It'll make more sense to do it after the webpage and it's backend are done anyway. For now, I guess we should look for cool apps rather than more IITH related things.


As for cool app suggestions, I recently came across this web-based project - [Swip](https://github.com/paulsonnentag/swip). Can we make an app that does this better, and make a cool multiplayer game around it? Something like that.

**Comment by ayushpateria** [comment]
It doesn't make sense to work on just-for-fun projects under soc. It should be something which adds some real value as we'll be paying the students.

**Comment by CrazyByDefault** [comment]
As this is just a smaller scale SoC, we don't really need productive stuff. People will be more interested if it's a game or something rather than _another_ IITH thing. 

One thing we can do is replace the Dashboard Frontend project, and have an app instead. Backend will be there as is, and there will be an Android app to access it. Apart from that, we can have an Android Game.

@Gouthamve @Siddhartha1234 Opinions, pleej.

**Comment by gouthamve** [comment]
Agree with @ayushpateria here. No incentive for mentors here. If its fun, either the mentor will do it or the candidate should figure it out himself. I cannot see this working with mentoring.

And then there is the money....

**Comment by CrazyByDefault** [comment]
Alright, putting it up as-is.

**Pull request merged**
